/* Problem: Each new term in the Fibonacci sequence is generated by adding the 
 previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

*/





var sequence = [];

function fibonacci(n) {
 
    for (var index = 0; index < n; index++) {
        sequence.push(index < 2 ? index : (sequence[index - 2] + sequence[index - 1]));
    }
 
    return sequence;
}

function evens(num) {
    return num % 2 === 0;
}


fibonacci(34);

sequence.filter(evens);

var total = 0;
for(var x in sequence.filter(evens)) { total += sequence.filter(evens)[x]; }